apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
  annotations:
    commit_sha: ${GITHUB_SHA_URL}
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.16.100.100-172.16.100.200
