---
- hosts: all
  become: yes
  tasks:
    - name: Install kubeadm utils and cri
      block:
        - name: add keyrings
          shell:
            "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6A030B21BA07F4FB FEEA9169307EA071
 8B57C5C2836F4BEB 4D64390375060AA4 || true"
        - name: add kubernetes sources
          copy:
            dest: /etc/apt/sources.list.d/kubernetes.list
            content: deb http://apt.kubernetes.io/ kubernetes-xenial main
        - name: add libcontainers
          copy:
            dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
            content: deb [trusted=yes] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_21.04/ /
        - name: add libcontainers cri-o
          copy:
            dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.23.1.list
            content: deb [trusted=yes] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23:/1.23.1/xUbuntu_21.04/ /
        - name: apt update
          shell:
            "sudo apt update"
        - name: install kube pkgs
          apt:
            name:
              - kubelet=1.23.1-00
              - kubeadm=1.23.1-00
              - kubectl=1.23.1-00
              - cri-o=1.23.1~0
              - cri-o-runc=1.0.1~0
              - kubernetes-cni=0.8.7-00
            state: present
            allow_downgrade: yes
        - name: mark hold
          shell:
            "sudo apt-mark hold kubelet kubeadm kubectl cri-o cri-o-runc"
    - name: Install docker
      apt:
        name:
          - docker.io
        state: latest
        update_cache: true
    - name: Configure docker
      block:
        - name: Copy daemon.json
          copy:
            dest: /etc/docker/daemon.json
            content: |
              {
              "exec-opts": ["native.cgroupdriver=systemd"],
              "log-driver": "json-file",
              "bridge": "none",
              "storage-driver": "overlay2",
              "log-opts": {
              "max-size": "100m"
              }
              }
        - name: Restart docker
          ansible.builtin.service:
            name: docker
            state: restarted
    - name: install pre-reqs
      apt:
        name:
          - ntp
          - docker.io
          - containerd
          - sysstat
          - etcd-client
          - nfs-common
          - lm-sensors
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - net-tools
          - jq
          - ipvsadm
        state: latest
        update_cache: true
    - name: Configure kubelet
      copy:
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        content: |
          [Service]
          Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
          Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
          EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
          EnvironmentFile=-/etc/default/kubelet
          ExecStart=
          ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
    - name: Configure containerd
      block:
        - name: mkdir /etc/containerd
          shell:
            "sudo mkdir /etc/containerd"
        - name: Copy containerd.yaml
          become: true
          copy:
            src: ./files/containerd.toml
            dest: /etc/containerd/config.toml
            owner: root
            group: root
            mode: 0644
        - name: Restart containerd
          ansible.builtin.service:
            name: containerd
            state: restarted
    - name: enable cri-o service
      ansible.builtin.service:
        name: crio
        state: started
        enabled: true
