apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: ${CLOUDFLARE_API_TOKEN}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    ...
    solvers:
    - dns01:
        cloudflare:
          email: jeremymv2@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
