apiVersion: v1
kind: Namespace
metadata:
  name: tests
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-ethzero-cloud
  namespace: tests
spec:
  dnsNames:
    - ethzero.cloud
    - '*.ethzero.cloud'
  secretName: test-ethzero-cloud-cert-tls
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: letsencrypt-staging
