apiVersion: v1
kind: Namespace
metadata:
  name: tests
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: tests
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: tests
spec:
  dnsNames:
    - ethzero.cloud
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
