# https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: "${CLUSTER_NAME}"
kubernetesVersion: ${K8S_VERSION}
controlPlaneEndpoint: "${CONTROL_PLANE_API}"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  criSocket: ${CRI_SOCKET}
discovery:
  bootstrapToken:
    token: "9a08jv.c0izixklcxtmnze7"
    apiServerEndpoint: "${CONTROL_PLANE_API}"
    unsafeSkipCAVerification: true
ignorePreflightErrors:
  - Mem
